apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: new-pubsub-tutorial
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/cloudsql-instances: supple-cosine-292623:us-central1:cloud-run-db
    spec:
      containerConcurrency: 80
      containers:
      - env:
        - name: PROJECT_ID
          value: supple-cosine-292623
        - name: OUT_BUCKET
          value: supple-cosine-292623-out-bucket
        image: gcr.io/supple-cosine-292623/pubsub:v0.0.3
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: '4'
            memory: 2Gi
      serviceAccountName: tutorial-service@supple-cosine-292623.iam.gserviceaccount.com
      timeoutSeconds: 3600
  traffic:
  - latestRevision: true
    percent: 100
